# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'RXTensions', :git => 'https://github.com/degordian/RxTensions.git', :branch => 'master'
  pod 'CoconutBits', :git => 'https://github.com/degordian/CoconutBits.git', :branch => 'swift5'
  pod 'SnapKit', '~> 5.0.0'
  pod "RxGesture"
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 5.2.0'
end
